name: build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: bufbuild/buf-setup-action@v0.7.0

      - name: make lint
        uses: bufbuild/buf-lint-action@v1.0.0
