name: build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - uses: bufbuild/buf-setup-action@v0.3.1

      - name: make lint
        uses: bufbuild/buf-lint-action@v0.3.0
